# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Syntax-Highlight-Perl
version:      1.01
version_from: lib/Apache/Syntax/Highlight/Perl.pm
installdirs:  site
requires:
    mod_perl:                      1.24
    Syntax::Highlight::Perl:       1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
